### ISSUE TITLE
推送功能

### ISSUE THREAD

**Issue by Jikexiaobai** [SlightDust/daxuexi_HoshinoBot#1]
能否增加一个大学习更新之后，发送消息的功能，就差不多是订阅B站投稿那样。

**Comment by SlightDust** [comment]
好的我试一下。现在不确定本期大学习关闭之后获取信息的地址的响应是什么，周日晚上我先看一下响应，然后改进一下。

**Comment by Jikexiaobai** [comment]
!!!好的，十分感谢，我发现这里：https://h5.cyol.com/special/weixin/sign.json

最后面 已经有了第十二季第四期的网址，但好像大部分公众号都还没有更新(比如 安徽共青团)

**Comment by Jikexiaobai** [comment]
> 好我试一下。现在了解本期大学习关闭之后获取信息的地址的响应是什么，周日晚上我先看一下响应，然后解决一下。

！！！好的，十分感谢，我发现这里：https : //h5.cyol.com/special/weixin/sign.json

最后面已经有了第十二季第四期的网址，但好像大多数公众号都还没有更新（比如安徽共青团）

**Comment by SlightDust** [comment]
> > 好我试一下。现在了解本期大学习关闭之后获取信息的地址的响应是什么，周日晚上我先看一下响应，然后解决一下。
> 
> ！！！好的，十分感谢，我发现这里：https : //h5.cyol.com/special/weixin/sign.json
> 
> 最后面已经有了第十二季第四期的网址，但好像大多数公众号都还没有更新（比如安徽共青团）

公众号没更的话查出来也没用23333，刚刚看了一下，青春湖北也没更。估计公众号和查状态那个地址是同步更新的。
