### ISSUE TITLE
报错啦，请问这个怎么解决

### ISSUE THREAD

**Issue by tuanzi66** [SlightDust/daxuexi_HoshinoBot#2]
前几天还用的好好的
![%1CUB3%Q06V%U5T 6TA7T%O](https://user-images.githubusercontent.com/101592087/159209775-a2670fe1-e844-47e7-b412-c5c095c83f11.png)

**Comment by SonderXiaoming** [comment]
同样报错，应该是获取的答案出了问题，等作者修复吧

**Comment by SonderXiaoming** [comment]
更新一下就可以解决

**Comment by tuanzi66** [comment]
> 更新一下就可以解决

请问怎么更新

**Comment by SonderXiaoming** [comment]
> > 更新一下就可以解决
> 
> 请问怎么更新

删了重装或者指令git pull

**Comment by SlightDust** [comment]
最新代码应该没问题
