### ISSUE TITLE
还是不行，超时捏

### ISSUE THREAD

**Issue by SonderXiaoming** [SlightDust/daxuexi_HoshinoBot#3]
![image](https://github.com/user-attachments/assets/a1c7f7f5-9567-4753-a2f6-dd469f24ac59)

**Comment by SlightDust** [comment]
我试没问题呀，浏览器直接访问https://h5.cyol.com/special/daxuexi/go6skq1n5a/index.html 能打开吗

**Comment by SonderXiaoming** [comment]
![image](https://github.com/user-attachments/assets/7ce21035-50d1-44b4-be2a-a236d2f74036)
难道因为我是海外ip？

**Comment by SonderXiaoming** [comment]
![image](https://github.com/user-attachments/assets/27509c70-28ea-4ca6-b319-1766ac978e8f)
难道因为我是海外

**Comment by SonderXiaoming** [comment]
md，还真是，屏蔽海外ip了
嘤嘤嘤
